name: CI Pipeline

on: [push, pull_request]

jobs:
  backend-lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Lint backend code
      run: | # Ignore line length (E501) and line break before operator (W503)
        cd backend
        pip install flake8
        flake8 --ignore=E501,W503 .